# Generated by Django 5.1.6 on 2025-02-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Some article', max_length=50, verbose_name='Name of article')),
                ('anons', models.CharField(default='Anons', max_length=250, verbose_name='Anons of article')),
                ('full_test', models.TextField(verbose_name='Full text of article')),
                ('date', models.DateTimeField(verbose_name='Time of publication')),
            ],
        ),
    ]
