# Generated by Django 5.1.6 on 2025-02-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='full_test',
            new_name='full_text',
        ),
    ]
